name: Build Documentation

on:
  push:
    branches:
      - master

jobs:
  build_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Install Tools
        run: |
          sudo apt-get install dbtoepub docbook-xsl fop libsaxon-java libxml2-utils libxslthl-java xsltproc

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Get phing
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: phing:3.0.0-alpha4

      - name: Build documentation
        run: phing -verbose

      - name: Check output folder
        run: ls -la out
      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@3.7.1
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     BRANCH: gh-pages
      #     FOLDER: out
