name: Build Documentation

on:
  push:
    branches:
      - master

jobs:
  build_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Install Tools
        run: apt-get install dbtoepub docbook-xsl fop libsaxon-java libxml2-utils libxslthl-java xsltproc && rvm use system

      - name: Build Documentation
        uses: phingofficial/phing-github-action@main
        with:
          version: 3.0.0-alpha4

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
